apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-ml-api
  template:
    metadata:
      labels:
        app: iris-ml-api
    spec:
      containers:
        - name: iris-ml-api
          image: localhost/iris-ml-api:1.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

